common has been updated from legacy codebase

diff --git a/multipoint-zigbee/common/Dockerfile b/multipoint-zigbee/common/Dockerfile
--- a/multipoint-zigbee/common/Dockerfile
+++ b/multipoint-zigbee/common/Dockerfile
@@ -4,7 +4,9 @@ FROM $BUILD_FROM as base
 ENV LANG C.UTF-8
 ARG BUILD_VERSION
 
-RUN apk add --no-cache socat tini nodejs
+RUN apk add --no-cache socat tini nodejs eudev && \
+    # Validation to confirm that curl is installed in the base image.
+    curl --version || (echo "curl missing" && exit 1)
 
 # Dependencies and build
 FROM base as dependencies_and_build
@@ -20,7 +22,7 @@ RUN apk add --no-cache --virtual .buildtools npm make gcc g++ linux-headers udev
     else \
         echo "Installing Stable version ${BUILD_VERSION%-*}" && \
         curl -sL -o "/app.tar.gz" \
-        "https://github.com/Koenkk/zigbee2mqtt/archive/${BUILD_VERSION%-*}.tar.gz" && \
+        "https://github.com/Koenkk/zigbee2mqtt/archive/refs/tags/${BUILD_VERSION%-*}.tar.gz" && \
         tar xzvf "/app.tar.gz"  && rm "/app.tar.gz" && \
         mv -v "zigbee2mqtt-${BUILD_VERSION%-*}" app && \
         mkdir /app/dist && \
@@ -28,13 +30,14 @@ RUN apk add --no-cache --virtual .buildtools npm make gcc g++ linux-headers udev
     fi; \
     echo "Installed Zigbee2MQTT @ version $(cat /app/dist/.hash)" && \
     cd /app && \
-    npm ci --no-audit --no-optional --no-update-notifier --unsafe-perm && \
-    npm run build && \
+    npm install -g $(jq -r '.packageManager' package.json) && \
+    pnpm install --frozen-lockfile --no-optional --unsafe-perm && \
+    pnpm run build && \
     rm -rf node_modules && \
-    npm ci --no-audit --no-optional --no-update-notifier --production --unsafe-perm && \
-    # Serialport needs to be rebuild for Alpine https://serialport.io/docs/9.x.x/guide-installation#alpine-linux
-    npm rebuild --build-from-source && \
-    apk del .buildtools
+    pnpm install --frozen-lockfile --no-optional --unsafe-perm --prod && \
+    # force serialport to rebuild on current platform instead of using prebuilds
+    rm -rf `find ./node_modules/.pnpm/ -wholename "*/@serialport/bindings-cpp/prebuilds" -type d` && \
+    pnpm rebuild @serialport/bindings-cpp
 
 # Release
 FROM base as release
@@ -47,5 +50,8 @@ COPY --from=dependencies_and_build /app/dist ./dist
 COPY --from=dependencies_and_build /app/package.json /app/LICENSE /app/index.js ./
 
 ENV NODE_ENV production
+
+HEALTHCHECK --interval=1m --timeout=3s --start-period=30s --start-interval=3s \
+  CMD curl -f http://localhost:8099/
 
 ENTRYPOINT [ "/sbin/tini", "--", "/docker-entrypoint.sh"]
